# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-23 06:14
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SharedDaimokuSessionEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time_millis', models.IntegerField()),
                ('end_time_millis', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='SharedDaimokuTarget',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60)),
                ('description', models.TextField()),
                ('target_count', models.IntegerField()),
                ('target_date_millis', models.IntegerField()),
                ('create_date_millis', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_state', models.CharField(choices=[(b'OI', b'OnlineIdle'), (b'OC', b'OnlineChanting'), (b'OF', b'Offline')], default=b'OF', max_length=2)),
                ('last_seen', models.DateTimeField()),
                ('status', models.CharField(max_length=300)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='shareddaimokutarget',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bodhibuddyapp.UserProfile'),
        ),
        migrations.AddField(
            model_name='shareddaimokusessionentry',
            name='contributor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bodhibuddyapp.UserProfile'),
        ),
    ]
