# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-23 06:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bodhibuddyapp', '0002_auto_20161023_0621'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='last_seen',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='status',
        ),
    ]
