# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-18 07:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=60)),
                ('campaign_type', models.CharField(choices=[(b'DA', b'Daimoku'), (b'HV', b'Home Visit'), (b'DL', b'Dialogue')], default=b'DA', max_length=2)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('target_value', models.PositiveIntegerField()),
                ('target_unit', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Daimoku',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_name', models.CharField(max_length=60)),
                ('member_email', models.CharField(max_length=60)),
                ('duration_minutes', models.PositiveIntegerField()),
                ('daimoku_date', models.DateField()),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dialogues.Campaign')),
            ],
        ),
        migrations.CreateModel(
            name='Dialogue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_name', models.CharField(max_length=60)),
                ('friend_name', models.CharField(max_length=60)),
                ('member_email', models.CharField(max_length=60)),
                ('dialogue_date', models.DateField()),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dialogues.Campaign')),
            ],
        ),
        migrations.CreateModel(
            name='HomeVisit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visitor_name', models.CharField(max_length=30)),
                ('visited_name', models.CharField(max_length=30)),
                ('visitor_email', models.CharField(max_length=30)),
                ('visit_date', models.DateField()),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dialogues.Campaign')),
            ],
        ),
    ]
