# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-21 02:58
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Dialogue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_name', models.CharField(max_length=60)),
                ('friend_name', models.CharField(max_length=60)),
                ('member_email', models.CharField(max_length=60)),
                ('dialogue_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='GA',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='GuestInvite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_name', models.CharField(max_length=30)),
                ('friend_name', models.CharField(max_length=30)),
                ('member_email', models.CharField(max_length=30)),
                ('invite_date', models.DateField()),
                ('info', models.TextField(blank=True)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dialogues.District')),
            ],
        ),
        migrations.CreateModel(
            name='HomeVisit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visitor_name', models.CharField(max_length=30)),
                ('visited_name', models.CharField(max_length=30)),
                ('visitor_email', models.CharField(max_length=30)),
                ('visit_date', models.DateField()),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dialogues.District')),
            ],
        ),
        migrations.CreateModel(
            name='Leader',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=60, unique=True)),
                ('phone', models.CharField(blank=True, max_length=15, validators=[django.core.validators.RegexValidator(message=b"Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex=b'^\\+?1?\\d{9,15}$')])),
            ],
        ),
        migrations.AddField(
            model_name='ga',
            name='leader',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dialogues.Leader'),
        ),
        migrations.AddField(
            model_name='district',
            name='leader',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dialogues.Leader'),
        ),
        migrations.AddField(
            model_name='district',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dialogues.Chapter'),
        ),
        migrations.AddField(
            model_name='dialogue',
            name='district',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dialogues.District'),
        ),
        migrations.AddField(
            model_name='chapter',
            name='leader',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dialogues.Leader'),
        ),
        migrations.AddField(
            model_name='chapter',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dialogues.Area'),
        ),
        migrations.AddField(
            model_name='area',
            name='leader',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dialogues.Leader'),
        ),
        migrations.AddField(
            model_name='area',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dialogues.GA'),
        ),
    ]
