# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-21 20:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dialogue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_name', models.CharField(max_length=60)),
                ('friend_name', models.CharField(max_length=60)),
                ('member_email', models.CharField(max_length=60)),
                ('dialogue_date', models.DateField()),
                ('my_story', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='HomeVisit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visitor_name', models.CharField(max_length=30)),
                ('visited_name', models.CharField(max_length=30)),
                ('visitor_email', models.CharField(max_length=30)),
                ('visit_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='struct_unit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('dialogue_count', models.BigIntegerField(null=True)),
                ('home_visit_count', models.BigIntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Area',
            fields=[
                ('struct_unit_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='dialogues.struct_unit')),
            ],
            bases=('dialogues.struct_unit',),
        ),
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('struct_unit_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='dialogues.struct_unit')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dialogues.Area')),
            ],
            bases=('dialogues.struct_unit',),
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('struct_unit_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='dialogues.struct_unit')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dialogues.Chapter')),
            ],
            bases=('dialogues.struct_unit',),
        ),
        migrations.CreateModel(
            name='GA',
            fields=[
                ('struct_unit_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='dialogues.struct_unit')),
            ],
            bases=('dialogues.struct_unit',),
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('struct_unit_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='dialogues.struct_unit')),
            ],
            bases=('dialogues.struct_unit',),
        ),
        migrations.AddField(
            model_name='homevisit',
            name='district',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dialogues.District'),
        ),
        migrations.AddField(
            model_name='ga',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dialogues.Region'),
        ),
        migrations.AddField(
            model_name='dialogue',
            name='district',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dialogues.District'),
        ),
        migrations.AddField(
            model_name='area',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dialogues.GA'),
        ),
    ]
