# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-23 14:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dialogues', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DaimokuCommitment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_name', models.CharField(max_length=60)),
                ('member_email', models.CharField(max_length=60)),
                ('duration_minutes', models.PositiveIntegerField()),
                ('committed_on_date', models.DateField()),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dialogues.Campaign')),
            ],
        ),
    ]
